In [96]:
import numpy as np
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [97]:
b.ndim

2

In [99]:
b1 = np.sum([[1,2,3],[4,5,6],[7,8,9]],axis=0)
print(b1)

[12 15 18]


In [100]:
c = np.ones((3,4))
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
c.ndim

2

In [101]:
d = np.arange(1,10,3)
print(d)

[1 4 7]


In [102]:
e = np.linspace(2,8,8)
print(e)

[2.         2.85714286 3.71428571 4.57142857 5.42857143 6.28571429
 7.14285714 8.        ]


## Filling same number in an array

In [104]:
f = np.full((3,4),10)
print(f)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


## Generating random numbers

In [105]:
g = np.random.random((2,3))
print(g)

[[0.09722953 0.46043609 0.50823474]
 [0.85986027 0.59875431 0.06623478]]


In [106]:
g.shape

(2, 3)

## Rearranging arrays

In [112]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a.shape = (4,2)
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [114]:
x10 = np.arange(16).reshape(2,8)
print(x10)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [115]:
x2 = np.array([1,2,3,4])
x3 = np.array([5,6,7,8])
x4 = np.multiply(x2,x3)
print(x4)

[ 5 12 21 32]


In [117]:
print(np.exp(x2))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [118]:
print("sqrt of array : " ,np.sqrt(x4))

sqrt of array :  [2.23606798 3.46410162 4.58257569 5.65685425]


In [119]:
print("sin of array : " ,np.sin(x3))

sin of array :  [-0.95892427 -0.2794155   0.6569866   0.98935825]


In [18]:
print(np.corrcoef(x4))

1.0


In [120]:
x5 = np.array([[0,1,2,4],[6,8,10,12],[14,16,18,20]])
x6 = np.array([3,4,7,8])

print("Broadcast :",x5+x6)

Broadcast : [[ 3  5  9 12]
 [ 9 12 17 20]
 [17 20 25 28]]


In [121]:
x7 = np.hstack((x3,x4))
print(x7)

[ 5  6  7  8  5 12 21 32]


In [122]:
x8 = np.vstack((x3,x4))
print(x8)

[[ 5  6  7  8]
 [ 5 12 21 32]]


In [123]:
x9 = np.concatenate((x3,x4))
print(x9)

[ 5  6  7  8  5 12 21 32]


In [124]:
x = np.array([[1, 2], [3, 4],[5,6]])
y = np.array([[7, 8],[9,10],[11,12]])

In [127]:
z = np.concatenate((x, y), axis=1)

In [128]:
z

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [132]:
z.min(axis=1)

array([1, 3, 5])

In [65]:
a1 = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [70]:
np.unique(a1)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [134]:
z.ravel()

array([ 1,  2,  7,  8,  3,  4,  9, 10,  5,  6, 11, 12])

In [135]:
def square(a):
    return a**2

In [136]:
x11 = square(z.flatten())

In [137]:
x11

array([  1,   4,  49,  64,   9,  16,  81, 100,  25,  36, 121, 144],
      dtype=int32)

In [138]:
np.hsplit(x10,4)

[array([[0, 1],
        [8, 9]]),
 array([[ 2,  3],
        [10, 11]]),
 array([[ 4,  5],
        [12, 13]]),
 array([[ 6,  7],
        [14, 15]])]

In [139]:
### dot product
a=np.array([[1,2],[3,4]])
b=np.array([[11,12],[13,14]])

In [140]:
print("dot product :",a.dot(b))

dot product : [[37 40]
 [85 92]]


In [6]:
print("inner product :",np.inner(a,b))

inner product : [[35 41]
 [81 95]]


In [7]:
a

array([[1, 2],
       [3, 4]])

In [8]:
b

array([[11, 12],
       [13, 14]])

In [141]:
x = np.matrix("10.;20.")
print(x)

[[10.]
 [20.]]


In [142]:
### Matrix vector multiplication
A = np.matrix([[1.,2], [3,4], [5,6]])
print(A*x)

[[ 50.]
 [110.]
 [170.]]


### Matrix Multiplication

In [29]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 

In [30]:
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [9]:
np.inner(a1,b1)

array([[35, 41],
       [81, 95]])

### Principal Component Analysis

Principal Components represent the directions of the data that specify a maximum amount of variance i.e. the lines that capture most information present in the data

1. Standardization of the continuous variables of the dataset.

2. Computing the Co-variance Matrix to identify Co-relations.

3. Computing the Eigen Values and Eigenvectors of the covariance Matrix to identify the Principal Components.

4. Deciding on the Principal Components to be kept for further analysis based on the variation in the Components using the Scree Plot.

5. Recast the data along the Principal Component’s axes.

In [ ]:
A*v =   l*v

In [78]:
a2 = np.array([[-6,3], [4,5]])  
b2 = np.array([1, 4])

In [143]:
np.dot(a2,b2)

array([ 6, 24])

In [ ]:
6*b2

In [144]:
a3 = np.array([[2,0,0],[0,4,5]
              ,[0,4,3]])  
b3 = np.array([0,1,-1])

In [145]:
np.dot(a3,b3)

array([ 0, -1,  1])

In [ ]:
-1*b3

In [85]:
import pandas as pd

In [86]:
pd.options.display.float_format = '{:20,.2f}'.format

In [82]:
cov_matrix = np.cov(a2.T)
print('Covariance Matrix :', cov_matrix)

Covariance Matrix : [[50. 10.]
 [10.  2.]]


In [88]:
eig_vals, eig_vecs = np.linalg.eig(cov_matrix)
print('n Eigen Values :', eig_vals)
print('Eigen Vectors :', eig_vecs)

n Eigen Values : [ 5.20000000e+01 -3.88578059e-16]
Eigen Vectors : [[ 0.98058068 -0.19611614]
 [ 0.19611614  0.98058068]]
